# 텍스트 전처리

In [2]:
# Downloading nltk packages
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /Users/zinwaiyan/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/zinwaiyan/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/zinwaiyan/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/zinwaiyan/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/zinwaiyan/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading pac

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    | 
[nltk_data]  Done downloading collection all


## 토큰화(Tokenization)

In [3]:
# 문장 토큰화
from nltk import sent_tokenize
text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text_sample)
print(type(sentences),len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [4]:
# 단어 토큰화
from nltk import word_tokenize
sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words),len(words))
print(words)


<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [5]:
# Combining sentence & word tokens
from nltk import word_tokenize, sent_tokenize
def tokenize_text(text):
    sentences = sent_tokenize(text)
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

word_tokens = tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


## Stop Words 제거

In [6]:
print('영어 stop words 개수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [7]:
# Filter stopwords
import nltk
stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
for sentence in word_tokens:
    filtered_words = []
    for word in sentence:
        word = word.lower()
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)
print(all_tokens)


[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


## Stemming & Lemmatization

In [ ]:
# Stemming
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest')) 
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [9]:
# Lemmatization 
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

amuse amuse amuse
happy happy
fancy fancy


# Bag of Words (BOW)

In [ ]:
# Sparse Matrix - COO form
import numpy as np
dense = np.array([[3,0,1],[0,2,0]])
from scipy import sparse
# data points that are not 0
data = np.array([3,1,2])
# row,col of not 0 data points
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])
# change into coo form
sparse_coo = sparse.coo_matrix((data,(row_pos,col_pos)))

# Print
cprint(sparse_coo.toarray())

[[3 0 1]
 [0 2 0]]


In [17]:
# Sparse Matrix - COO form + CSR form 
from scipy import sparse
dense2 = np.array([[0, 0, 1, 0, 0, 5],
            [1, 4, 0, 3, 2, 5],
            [0, 6, 0, 3, 0, 0],
            [2, 0, 0, 0, 0, 0],
            [0, 0, 0, 7, 0, 8],
            [1, 0, 0, 0, 0, 0]])
# data points that are not 0
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
# row,col of data points that are not 0
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])
# change into coo form
sparse_coo = sparse.coo_matrix((data2,(row_pos,col_pos)))

# start index for each row_pos + total num(13)
row_pos_ind = np.array([0,2,7,9,10,12,13])
# change into csr form
sparse_csr = sparse.csr_matrix((data2,col_pos,row_pos_ind))

# Print
print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [22]:
# Real-life Use
dense3 = np.array([[0, 0, 1, 0, 0, 5],
            [1, 4, 0, 3, 2, 5],
            [0, 6, 0, 3, 0, 0],
            [2, 0, 0, 0, 0, 0],
            [0, 0, 0, 7, 0, 8],
            [1, 0, 0, 0, 0, 0]])
COO = sparse.coo_matrix(dense3)
CSR = sparse.csr_matrix(dense3)

print("COO Form:")
print(COO)
print("CSR Form:")
print(CSR)

COO Form:
  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
CSR Form:
  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1


# 감성 분석(Sentiment Analysis)

## Sentiment Analysis based on Supervised Learning

### IMDB movies dataset

In [ ]:
# Using IMDB movies review dataset 
import pandas as pd
# Load dataset
review_df = pd.read_csv('labeledTrainData.tsv',header=0,sep='\t',quoting=3)
review_df.head(3)

,id,sentiment,review
0,"""5814_8""",1,"""With all this stuff going down at the moment ..."
1,"""2381_9""",1,"""\""The Classic War of the Worlds\"" by Timothy ..."
2,"""7759_3""",0,"""The film starts with a manager (Nicholas Bell..."


In [46]:
# sentiment 
    # 1 : positive, 0: negative

In [47]:
print(review_df['review'][0])

"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally sta

In [48]:
import re

# replacing <br> tag with ''
review_df['review'] = review_df['review'].str.replace('<br />',' ')

# replace special characters with '' using re module (regular expression) 
review_df['review'] = review_df['review'].apply(lambda x:re.sub("[^a-zA-Z]"," ",x))

In [49]:
# Split data set into Train & Test
from sklearn.model_selection import train_test_split
# Target value
class_df = review_df['sentiment']
# Feature value(Review)
feature_df = review_df.drop(['id','sentiment'],axis=1,inplace=False)

# Split
X_train,X_test,y_train,y_test = train_test_split(feature_df,class_df,test_size=0.3,random_state=156)
print(X_train.shape,X_test.shape)

(17500, 1) (7500, 1)


In [50]:
print(X_train[:3])
print(y_train[:3])
print()
print(type(X_train))
print(type(y_train))

                                                  review
3724    This version moved a little slow for my taste...
23599   I really enjoyed this film because I have a t...
11331   Saw this in the theater in     and fell out o...
3724     0
23599    1
11331    1
Name: sentiment, dtype: int64

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [51]:
# Feature Vectorization -> Logistic Regression -> Predict using Accuracy & ROC-AUC
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

# Using CountVectorizer & Logistic Regression
pipeline = Pipeline([
    ('cnt_vect',CountVectorizer(stop_words='english',ngram_range=(1,2))),
    ('lr_clf',LogisticRegression(solver='liblinear',C=10))
])

# Fit
pipeline.fit(X_train['review'],y_train)
# Predict
pred = pipeline.predict(X_test['review'])
pred_probs = pipeline.predict_proba(X_test['review'])[:,1]
# Print
print('예측 정확도는 {0:.4f}, ROC-AUC는 {1:.4f}'.format(accuracy_score(y_test, pred), roc_auc_score(y_test, pred_probs)))


예측 정확도는 0.8860, ROC-AUC는 0.9503


In [52]:
# Using TFidVectorizer & Logistic Regression
pipeline = Pipeline([
    ('tfidf_vect',TfidfVectorizer(stop_words='english',ngram_range=(1,2))),
    ('lr_clf',LogisticRegression(solver='liblinear',C=10))
])

# Fit
pipeline.fit(X_train['review'],y_train)
# Predict
pred = pipeline.predict(X_test['review'])
pred_probs = pipeline.predict_proba(X_test['review'])[:,1]
# Print
print('예측 정확도는 {0:.4f}, ROC-AUC는 {1:.4f}'.format(accuracy_score(y_test, pred), roc_auc_score(y_test, pred_probs)))


예측 정확도는 0.8936, ROC-AUC는 0.9598


## Sentiment Analysis based on Unsupervised Learning

### WordNet

In [ ]:
# Using synsets()
    # dictionary including POS, definition, lemmas
from nltk.corpus import wordnet as wn
term = "present"

synsets = wn.synsets(term)
print('synsets() 반환 type :',type(synsets))
print('synsets() 반환 값 개수:', len(synsets)) 
print('synsets() 반환 값 :', synsets)

print()

# Printing Name, POS, Definition, Lemmas
for synset in synsets:
    print('##### Synset name :',synset.name(),'#####')
    print('POS :',synset.lexname())
    print('Definition:',synset.definition())
    print('Lemmas:',synset.lemma_names())

synsets() 반환 type : <class 'list'>
synsets() 반환 값 개수: 18
synsets() 반환 값 : [Synset('present.n.01'), Synset('present.n.02'), Synset('present.n.03'), Synset('show.v.01'), Synset('present.v.02'), Synset('stage.v.01'), Synset('present.v.04'), Synset('present.v.05'), Synset('award.v.01'), Synset('give.v.08'), Synset('deliver.v.01'), Synset('introduce.v.01'), Synset('portray.v.04'), Synset('confront.v.03'), Synset('present.v.12'), Synset('salute.v.06'), Synset('present.a.01'), Synset('present.a.02')]

##### Synset name : present.n.01 #####
POS : noun.time
Definition: the period of time that is happening now; any continuous stretch of time including the moment of speech
Lemmas: ['present', 'nowadays']
##### Synset name : present.n.02 #####
POS : noun.possession
Definition: something presented as a gift
Lemmas: ['present']
##### Synset name : present.n.03 #####
POS : noun.communication
Definition: a verb tense that expresses actions or states at the time of speaking
Lemmas: ['present', 'present

In [ ]:
# Measuring similarity between words using WordNet
tree = wn.synset('tree.n.01')
lion = wn.synset('lion.n.01')
tiger = wn.synset('tiger.n.02') 
cat = wn.synset('cat.n.01') 
dog = wn.synset('dog.n.01')

entities = [tree,lion,tiger,cat,dog]
similarities = []
# Entities' name
entity_names = [entity.name().split('.')[0] for entity in entities]
# Find similarity
for entity in entities:
    similarity = [round(entity.path_similarity(compared_entity),2) for compared_entity in entities]
    similarities.append(similarity)
# Change into dataframe
similarity_df = pd.DataFrame(similarities,columns=entity_names,index=entity_names)
similarity_df

,tree,lion,tiger,cat,dog
tree,1.00,0.07,0.07,0.08,0.12
lion,0.07,1.00,0.33,0.25,0.17
tiger,0.07,0.33,1.00,0.25,0.17
cat,0.08,0.25,0.25,1.00,0.20
dog,0.12,0.17,0.17,0.20,1.00


### SentiWordNet 

In [ ]:
# Using senti_synsets()
import nltk
from nltk.corpus import sentiwordnet as swn 
senti_synsets = list(swn.senti_synsets('slow'))
print('senti_synsets() 반환 type ：', type(senti_synsets))
print('senti_synsets() 반환 값 개수:', len(senti_synsets))
print('senti_synsets() 반환 값 :', senti_synsets)

senti_synsets() 반환 type ： <class 'list'>
senti_synsets() 반환 값 개수: 11
senti_synsets() 반환 값 : [SentiSynset('decelerate.v.01'), SentiSynset('slow.v.02'), SentiSynset('slow.v.03'), SentiSynset('slow.a.01'), SentiSynset('slow.a.02'), SentiSynset('dense.s.04'), SentiSynset('slow.a.04'), SentiSynset('boring.s.01'), SentiSynset('dull.s.08'), SentiSynset('slowly.r.01'), SentiSynset('behind.r.03')]


In [60]:
# Using senti_synset()
father = swn.senti_synset('father.n.01')
print('father 긍정감성 지수: ', father.pos_score())
print ('fat her 부정감성 지수: ', father. neg_score ())
print('father 객관성 지수: ',father.obj_score())
print('\n')
fabulous = swn.senti_synset('fabulous.a.01')
print('fabulous 긍정감성 지수: ',fabulous.pos_score()) 
print('fabulous 부정감성 지수: ',fabulous.neg_score())

father 긍정감성 지수:  0.0
fat her 부정감성 지수:  0.0
father 객관성 지수:  1.0


fabulous 긍정감성 지수:  0.875
fabulous 부정감성 지수:  0.125


### Sentiment Analysis of Movies Review using SentiWordNet


In [72]:
# Change into POS Tag using NLTK PennTreebank Tag
def penn_to_wn(tag):
    if tag.startswith('J'):
        return wn.ADJ
    elif tag.startswith('N'):
        return wn.NOUN
    elif tag.startswith('R'):
        return wn.ADV
    elif tag.startswith('V'):
        return wn.VERB      

In [73]:
# Calculate Polarity Score
    # Text -> Sentence Token -> Word Token -> POS Tagging -> Lemmatize -> Polarity Score
from nltk.stem import WordNetLemmatizer
from nltk.corpus import sentiwordnet as swn 
from nltk import sent_tokenize,word_tokenize,pos_tag

def swn_polarity(text):
    sentiment = 0.0
    tokens_count = 0
    # create Lemmatizer obj
    lemmatizer = WordNetLemmatizer()
    # Sentence token
    raw_sentences = sent_tokenize(text)
    for raw_sentence in raw_sentences:
        # Word token -> POS tag
        tagged_sentence = pos_tag(word_tokenize(raw_sentence))
        for word,tag in tagged_sentence:
            # change into wn_tag
            wn_tag = penn_to_wn(tag)
            if wn_tag not in (wn.NOUN,wn.ADJ,wn.ADV):
                continue
            # Lemmatize
            lemma = lemmatizer.lemmatize(word,pos=wn_tag)
            if not lemma:
                continue
            # Create synsets obj
            synsets = wn.synsets(lemma,pos=wn_tag)
            if not synsets:
                continue
            # Take first word in synsets list
            synset = synsets[0]
            # Calculate polarity score using SentiWordnet's function
            swn_synset = swn.senti_synset(synset.name())
            sentiment += (swn_synset.pos_score()-swn_synset.neg_score())
            tokens_count += 1
    if not tokens_count:
        return 0
    # Return 1(positive) if sentiment>=0
    if sentiment >= 0:
        return 1
    return 0
    


In [65]:
from nltk import pos_tag
print(pos_tag(['slow']))

[('slow', 'VB')]


In [ ]:
# Applying Polarity score function to all reviews in review_df
review_df['preds'] = review_df['review'].apply(lambda x:swn_polarity(x))
# For prediction score calculation
y_target = review_df['sentiment'].values
preds = review_df['preds'].values


In [75]:
# Calculate prediction score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from sklearn.metrics import recall_score, f1_score,roc_auc_score
import numpy as np
print(confusion_matrix(y_target,preds))
print("정확도:", np.round(accuracy_score(y_target, preds), 4))
print("정밀도:", np.round(precision_score(y_target, preds), 4))
print("재현율:", np.round(recall_score(y_target, preds), 4))

[[7669 4831]
 [3635 8865]]
정확도: 0.6614
정밀도: 0.6473
재현율: 0.7092


### Sentiment Analysis using VADER

In [76]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
senti_analyzer = SentimentIntensityAnalyzer()
senti_scores = senti_analyzer.polarity_scores(review_df['review'][0])
print(senti_scores)

{'neg': 0.13, 'neu': 0.743, 'pos': 0.127, 'compound': -0.7943}


In [78]:
# Calculate polarity score
def vader_polarity(review,threshold=0.1):
    # Calculate polarity score
    analyzer = SentimentIntensityAnalyzer()
    scores = analyzer.polarity_scores(review)
    # if value of compound > threshold
    agg_score = scores['compound']
    final_sentiment = 1 if agg_score > threshold else 0
    return final_sentiment    

In [79]:
# Apply polarity score to all reviews in review_df
review_df['vader_preds'] = review_df['review'].apply(lambda x:vader_polarity(x,0.1))
# For prediction score calculation
y_target = review_df['sentiment'].values
vader_preds = review_df['vader_preds'].values
# Calculate prediction score
print(confusion_matrix(y_target,vader_preds))
print("정확도:", np.round(accuracy_score(y_target, vader_preds),4))
print("정밀도:", np.round(precision_score(y_target , vader_preds),4)) 
print("재현율:", np.round(recall_score(y_target, vader_preds),4))

[[ 6747  5753]
 [ 1858 10642]]
정확도: 0.6956
정밀도: 0.6491
재현율: 0.8514
